### ISSUE TITLE
请教帮忙解惑一下原理框图

### ISSUE THREAD

**Issue by semchan** [lichao-sun/SoraReview#1]
![4d6a21c8ef5b7ae571e305a32e08d5c8](https://github.com/lichao-sun/SoraReview/assets/20419555/8e5ab580-eb74-4d85-b911-7b4a755f4531)
非常感谢您的逆向工程分析。对于您论文中的原理框图，我有一些不太理解的地方，可否予以解释？感谢！
1.如图所示，两个部分（红色部分）的ZT是相同的吗？
2.Diffusion Transformer Block和前面的箭头模块是同一个吗？或者有别的什么解释？
3.当图片或视频帧进行引导的时候是否可以完成两个视频的融合？我的理解是，两个视频融合时，应当通过VAE的Encoder提取对应的特征，才能更好的实现融合，不知道正确否？

**Comment by taokz** [comment]
@semchan 您好，感谢您对我们工作的关注。关于您的几个问题：
1. 去噪之后应该是 Z 而不是 Z_T, 我们这里出现了笔误。我们在后续版本会更正这个信息。
2. 是的。参考 latent diffusion model 的示意图。
3. 我和您持相同的意见。但是提出来的特征不一定是conditioning，具体方法可能是 SDdit (SDEdit: Guided Image Synthesis and Editing with Stochastic Differential Equations。 此外，我个人认为需要额外的文本prompt引导更平滑的过渡，类似“connect these two videos”.

**Comment by semchan** [comment]
> @semchan 您好，感谢您对我们工作的关注。关于您的几个问题：
> 
> 1. 去噪之后应该是 Z 而不是 Z_T, 我们这里出现了笔误。我们在后续版本会更正这个信息。
> 2. 是的。参考 latent diffusion model 的示意图。
> 3. 我和您持相同的意见。但是提出来的特征不一定是conditioning，具体方法可能是 SDdit (SDEdit: Guided Image Synthesis and Editing with Stochastic Differential Equations。 此外，我个人认为需要额外的文本prompt引导更平滑的过渡，类似“connect these two videos”.

感谢回复
